# Generated by Django 5.0.2 on 2024-02-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileTrams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='file/')),
                ('pattern', models.CharField(choices=[('latin', 'latin'), ('cyrillic', 'cyrillic')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TextTrans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('pattern', models.CharField(choices=[('latin', 'Latin'), ('cyrillic', 'Cyrillic')], max_length=20)),
            ],
        ),
    ]
